server:
  port: 8084

  spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/Juanandresfl/ms-microservicios.git
            searchPaths: config-data
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
    security:
      user:
        name: root
        password: secret


